#DisablePathCorrection: false
#EnablePathEscape: false
#FireMethodNotAllowed: true
#DisableBodyConsumptionOnUnmarshal: true
#TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
#Charset: UTF-8
#SSLProxyHeaders:
#  X-Forwarded-Proto: https
#HostProxyHeaders:
#  X-Host: true
#RemoteAddrHeaders:
#  - X-Real-Ip
#  - X-Forwarded-For
#  - CF-Connecting-IP
Other:
  Addr: :9000
  Mode: debug